language: java
jdk:
- oraclejdk8
branches:
  only:
    - master
#script:
#   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: problemoff
